export const FISICA_JURIDICA = 'FISICA_JURIDICA';
export const BTN_CLICKED_REQUEST = 'BTN_CLICKED_REQUEST';
export const BTN_CLICKED_SUCESS = 'BTN_CLICKED_SUCESS';
export const BTN_CLICKED_FAIL = 'BTN_CLICKED_FAIL';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';